<?php

namespace Database\Seeders;

use App\Models\MKelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    private $kelurahans = array(
        array("id_kecamatan" => 1, "kelurahan" => "ASEM ROWO"),
        array("id_kecamatan" => 1, "kelurahan" => "GENTING KALIANAK"),
        array("id_kecamatan" => 1, "kelurahan" => "TAMBAK SARIOSO"),
        array("id_kecamatan" => 2, "kelurahan" => "KANDANGAN"),
        array("id_kecamatan" => 2, "kelurahan" => "ROMOKALISARI"),
        array("id_kecamatan" => 2, "kelurahan" => "SEMEMI"),
        array("id_kecamatan" => 2, "kelurahan" => "TAMBAK OSO WILANGUN"),
        array("id_kecamatan" => 3, "kelurahan" => "ALUN-ALUN CONTONG"),
        array("id_kecamatan" => 3, "kelurahan" => "BUBUTAN"),
        array("id_kecamatan" => 3, "kelurahan" => "GUNDIH"),
        array("id_kecamatan" => 3, "kelurahan" => "JEPARA"),
        array("id_kecamatan" => 3, "kelurahan" => "TEMBOK DUKUH"),
        array("id_kecamatan" => 4, "kelurahan" => "BULAK"),
        array("id_kecamatan" => 4, "kelurahan" => "KEDUNG COWEK"),
        array("id_kecamatan" => 4, "kelurahan" => "KENJERAN"),
        array("id_kecamatan" => 4, "kelurahan" => "SUKOLILO BARU"),
        array("id_kecamatan" => 5, "kelurahan" => "DUKUH KUPANG"),
        array("id_kecamatan" => 5, "kelurahan" => "DUKUH PAKIS"),
        array("id_kecamatan" => 5, "kelurahan" => "GUNUNG SARI"),
        array("id_kecamatan" => 5, "kelurahan" => "PRADAH KALIKENDAL"),
        array("id_kecamatan" => 6, "kelurahan" => "DUKUH MENANGGAL"),
        array("id_kecamatan" => 6, "kelurahan" => "GAYUNGAN"),
        array("id_kecamatan" => 6, "kelurahan" => "KETINTANG"),
        array("id_kecamatan" => 6, "kelurahan" => "MENANGGAL"),
        array("id_kecamatan" => 7, "kelurahan" => "EMBONG KALIASIN"),
        array("id_kecamatan" => 7, "kelurahan" => "GENTENG"),
        array("id_kecamatan" => 7, "kelurahan" => "KAPASARI"),
        array("id_kecamatan" => 7, "kelurahan" => "KETABANG"),
        array("id_kecamatan" => 7, "kelurahan" => "PENELEH"),
        array("id_kecamatan" => 8, "kelurahan" => "AIRLANGGA"),
        array("id_kecamatan" => 8, "kelurahan" => "BARATAJAYA"),
        array("id_kecamatan" => 8, "kelurahan" => "GUBENG"),
        array("id_kecamatan" => 8, "kelurahan" => "KERTAJAYA"),
        array("id_kecamatan" => 8, "kelurahan" => "MOJO"),
        array("id_kecamatan" => 8, "kelurahan" => "PUCANG SEWU"),
        array("id_kecamatan" => 9, "kelurahan" => "GUNUNG ANYAR"),
        array("id_kecamatan" => 9, "kelurahan" => "GUNUNG ANYAR TAMBAK"),
        array("id_kecamatan" => 9, "kelurahan" => "RUNGKUT MENANGGAL"),
        array("id_kecamatan" => 9, "kelurahan" => "RUNGKUT TENGAH"),
        array("id_kecamatan" => 10, "kelurahan" => "JAMBANGAN"),
        array("id_kecamatan" => 10, "kelurahan" => "KARAH"),
        array("id_kecamatan" => 10, "kelurahan" => "KEBONSARI"),
        array("id_kecamatan" => 10, "kelurahan" => "PAGESANGAN"),
        array("id_kecamatan" => 11, "kelurahan" => "KARANG PILANG"),
        array("id_kecamatan" => 11, "kelurahan" => "KEBRAON"),
        array("id_kecamatan" => 11, "kelurahan" => "KEDURUS"),
        array("id_kecamatan" => 11, "kelurahan" => "WARU GUNUNG"),
        array("id_kecamatan" => 12, "kelurahan" => "BULAK BANTENG"),
        array("id_kecamatan" => 12, "kelurahan" => "SIDOTOPO WETAN"),
        array("id_kecamatan" => 12, "kelurahan" => "TAMBAK WEDI"),
        array("id_kecamatan" => 12, "kelurahan" => "TANAH KALI KEDINDING"),
        array("id_kecamatan" => 13, "kelurahan" => "DUPAK"),
        array("id_kecamatan" => 13, "kelurahan" => "KEMAYORAN"),
        array("id_kecamatan" => 13, "kelurahan" => "KREMBANGAN SELATAN"),
        array("id_kecamatan" => 13, "kelurahan" => "MOROKREMBANGAN"),
        array("id_kecamatan" => 13, "kelurahan" => "PERAK BARAT"),
        array("id_kecamatan" => 14, "kelurahan" => "BANGKINGAN"),
        array("id_kecamatan" => 14, "kelurahan" => "JERUK"),
        array("id_kecamatan" => 14, "kelurahan" => "LAKARSANTRI"),
        array("id_kecamatan" => 14, "kelurahan" => "LIDAH KULON"),
        array("id_kecamatan" => 14, "kelurahan" => "LIDAH WETAN"),
        array("id_kecamatan" => 14, "kelurahan" => "SUMURWELUT"),
        array("id_kecamatan" => 15, "kelurahan" => "DUKUH SUTOREJO"),
        array("id_kecamatan" => 15, "kelurahan" => "KALIJUDAN"),
        array("id_kecamatan" => 15, "kelurahan" => "KALISARI"),
        array("id_kecamatan" => 15, "kelurahan" => "KEJAWAAN PUTIH TAMBAK"),
        array("id_kecamatan" => 15, "kelurahan" => "MANYAR SABRANGAN"),
        array("id_kecamatan" => 15, "kelurahan" => "MULYOREJO"),
        array("id_kecamatan" => 16, "kelurahan" => "BONGKARAN"),
        array("id_kecamatan" => 16, "kelurahan" => "KREMBANGAN UTARA"),
        array("id_kecamatan" => 16, "kelurahan" => "NYAMPLUNGAN"),
        array("id_kecamatan" => 16, "kelurahan" => "PERAK TIMUR"),
        array("id_kecamatan" => 16, "kelurahan" => "PERAK UTARA"),
        array("id_kecamatan" => 17, "kelurahan" => "BABAT JERAWAT"),
        array("id_kecamatan" => 17, "kelurahan" => "BENOWO"),
        array("id_kecamatan" => 17, "kelurahan" => "PAKAL"),
        array("id_kecamatan" => 17, "kelurahan" => "SUMBER REJO"),
        array("id_kecamatan" => 18, "kelurahan" => "KALIRUNGKUT"),
        array("id_kecamatan" => 18, "kelurahan" => "KEDUNG BARUK"),
        array("id_kecamatan" => 18, "kelurahan" => "MEDOKAN AYU"),
        array("id_kecamatan" => 18, "kelurahan" => "PENJARINGANSARI"),
        array("id_kecamatan" => 18, "kelurahan" => "RUNGKUT KIDUL"),
        array("id_kecamatan" => 18, "kelurahan" => "WONOREJO"),
        array("id_kecamatan" => 19, "kelurahan" => "BERINGIN"),
        array("id_kecamatan" => 19, "kelurahan" => "LONTAR"),
        array("id_kecamatan" => 19, "kelurahan" => "MADE"),
        array("id_kecamatan" => 19, "kelurahan" => "SAMBIKEREP"),
        array("id_kecamatan" => 20, "kelurahan" => "BANYU URIP"),
        array("id_kecamatan" => 20, "kelurahan" => "KUPANG KRAJAN"),
        array("id_kecamatan" => 20, "kelurahan" => "PAKIS"),
        array("id_kecamatan" => 20, "kelurahan" => "PETEMON"),
        array("id_kecamatan" => 20, "kelurahan" => "PUTAT JAYA"),
        array("id_kecamatan" => 20, "kelurahan" => "SAWAHAN"),
        array("id_kecamatan" => 21, "kelurahan" => "AMPEL"),
        array("id_kecamatan" => 21, "kelurahan" => "PEGIRIAN"),
        array("id_kecamatan" => 21, "kelurahan" => "SIDOTOPO"),
        array("id_kecamatan" => 21, "kelurahan" => "UJUNG"),
        array("id_kecamatan" => 21, "kelurahan" => "WONOKUSUMO"),
        array("id_kecamatan" => 22, "kelurahan" => "KAPASAN"),
        array("id_kecamatan" => 22, "kelurahan" => "SIDODADI"),
        array("id_kecamatan" => 22, "kelurahan" => "SIMOKERTO"),
        array("id_kecamatan" => 22, "kelurahan" => "SIMOLAWANG"),
        array("id_kecamatan" => 22, "kelurahan" => "TAMBAKREJO"),
        array("id_kecamatan" => 23, "kelurahan" => "GEBANG PUTIH"),
        array("id_kecamatan" => 23, "kelurahan" => "KEPUTIH"),
        array("id_kecamatan" => 23, "kelurahan" => "KLAMPIS NGASEM"),
        array("id_kecamatan" => 23, "kelurahan" => "MEDOKAN SEMAMPIR"),
        array("id_kecamatan" => 23, "kelurahan" => "MENUR PUMPUNGAN"),
        array("id_kecamatan" => 23, "kelurahan" => "NGINDEN JANGKUNGAN"),
        array("id_kecamatan" => 23, "kelurahan" => "SEMOLOWARU"),
        array("id_kecamatan" => 24, "kelurahan" => "PUTAT GEDE"),
        array("id_kecamatan" => 24, "kelurahan" => "SIMOMULYO"),
        array("id_kecamatan" => 24, "kelurahan" => "SIMOMULYO BARU"),
        array("id_kecamatan" => 24, "kelurahan" => "SONOKWIJENAN"),
        array("id_kecamatan" => 24, "kelurahan" => "SUKOMANUNGGAL"),
        array("id_kecamatan" => 24, "kelurahan" => "TANJUNGSARI"),
        array("id_kecamatan" => 25, "kelurahan" => "DUKUH SETRO"),
        array("id_kecamatan" => 25, "kelurahan" => "GADING"),
        array("id_kecamatan" => 25, "kelurahan" => "KAPASMADYA BARU"),
        array("id_kecamatan" => 25, "kelurahan" => "PACARKELING"),
        array("id_kecamatan" => 25, "kelurahan" => "PACARKEMBANG"),
        array("id_kecamatan" => 25, "kelurahan" => "PLOSO"),
        array("id_kecamatan" => 25, "kelurahan" => "RANGKAH"),
        array("id_kecamatan" => 25, "kelurahan" => "TAMBAKSARI"),
        array("id_kecamatan" => 26, "kelurahan" => "BALONGSARI"),
        array("id_kecamatan" => 26, "kelurahan" => "BANJAR SUGIHAN"),
        array("id_kecamatan" => 26, "kelurahan" => "KARANG POH"),
        array("id_kecamatan" => 26, "kelurahan" => "MANUKAN KULON"),
        array("id_kecamatan" => 26, "kelurahan" => "MANUKAN WETAN"),
        array("id_kecamatan" => 26, "kelurahan" => "TANDES"),
        array("id_kecamatan" => 27, "kelurahan" => "DR. SOETOMO"),
        array("id_kecamatan" => 27, "kelurahan" => "KEDUNGDORO"),
        array("id_kecamatan" => 27, "kelurahan" => "KEPUTRAN"),
        array("id_kecamatan" => 27, "kelurahan" => "TEGALSARI"),
        array("id_kecamatan" => 27, "kelurahan" => "WONOREJO"),
        array("id_kecamatan" => 28, "kelurahan" => "KENDANGSARI"),
        array("id_kecamatan" => 28, "kelurahan" => "KUTISARI"),
        array("id_kecamatan" => 28, "kelurahan" => "PANJANG JIWO"),
        array("id_kecamatan" => 28, "kelurahan" => "TENGGILIS MEJOYO"),
        array("id_kecamatan" => 29, "kelurahan" => "BABATAN"),
        array("id_kecamatan" => 29, "kelurahan" => "BALAS KLUMPRIK"),
        array("id_kecamatan" => 29, "kelurahan" => "JAJAR TUNGGAL"),
        array("id_kecamatan" => 29, "kelurahan" => "WIYUNG"),
        array("id_kecamatan" => 30, "kelurahan" => "BENDUL MERISI"),
        array("id_kecamatan" => 30, "kelurahan" => "JEMUR WONOSARI"),
        array("id_kecamatan" => 30, "kelurahan" => "MARGOREJO"),
        array("id_kecamatan" => 30, "kelurahan" => "SIDOSERMO"),
        array("id_kecamatan" => 30, "kelurahan" => "SIWALANKERTO"),
        array("id_kecamatan" => 31, "kelurahan" => "DARMO"),
        array("id_kecamatan" => 31, "kelurahan" => "JAGIR"),
        array("id_kecamatan" => 31, "kelurahan" => "NGAGEL"),
        array("id_kecamatan" => 31, "kelurahan" => "NGAGEL REJO"),
        array("id_kecamatan" => 31, "kelurahan" => "SAWUNGGALING"),
        array("id_kecamatan" => 31, "kelurahan" => "WONOKROMO")
    );
    public function run()
    {
        foreach ($this->kelurahans as $key => $kelurahan) {
            MKelurahan::create($kelurahan);
        }
    }
}
