<?php

namespace Database\Seeders;

use App\Models\KuotaKelurahan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KuotaKelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    protected $updates = array(
        // array("kecamatan" => "ASEM ROWO", "kelurahan" => "ASEM ROWO", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "ASEM ROWO", "kelurahan" => "GENTING KALIANAK", "kuota_awal" => 3, "kuota_sisa" => 2),
        // array("kecamatan" => "ASEM ROWO", "kelurahan" => "TAMBAK SARIOSO", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "BENOWO", "kelurahan" => "KANDANGAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "BENOWO", "kelurahan" => "ROMOKALISARI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "BENOWO", "kelurahan" => "SEMEMI", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "BENOWO", "kelurahan" => "TAMBAK OSO WILANGUN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "BUBUTAN", "kelurahan" => "ALUN-ALUN CONTONG", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "BUBUTAN", "kelurahan" => "BUBUTAN", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "BUBUTAN", "kelurahan" => "GUNDIH", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "BUBUTAN", "kelurahan" => "JEPARA", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "BUBUTAN", "kelurahan" => "TEMBOK DUKUH", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "BULAK", "kelurahan" => "BULAK", "kuota_awal" => 3, "kuota_sisa" => 2),
        // array("kecamatan" => "BULAK", "kelurahan" => "KEDUNG COWEK", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "BULAK", "kelurahan" => "KENJERAN", "kuota_awal" => 2, "kuota_sisa" => 1),
        // array("kecamatan" => "BULAK", "kelurahan" => "SUKOLILO BARU", "kuota_awal" => 3, "kuota_sisa" => 2),
        // array("kecamatan" => "DUKUH PAKIS", "kelurahan" => "DUKUH KUPANG", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "DUKUH PAKIS", "kelurahan" => "DUKUH PAKIS", "kuota_awal" => 6, "kuota_sisa" => 5),
        // array("kecamatan" => "DUKUH PAKIS", "kelurahan" => "GUNUNG SARI", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "DUKUH PAKIS", "kelurahan" => "PRADAH KALIKENDAL", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "GAYUNGAN", "kelurahan" => "DUKUH MENANGGAL", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GAYUNGAN", "kelurahan" => "GAYUNGAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GAYUNGAN", "kelurahan" => "KETINTANG", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GAYUNGAN", "kelurahan" => "MENANGGAL", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GENTENG", "kelurahan" => "EMBONG KALIASIN", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "GENTENG", "kelurahan" => "GENTENG", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "GENTENG", "kelurahan" => "KAPASARI", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "GENTENG", "kelurahan" => "KETABANG", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "GENTENG", "kelurahan" => "PENELEH", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "GUBENG", "kelurahan" => "AIRLANGGA", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "GUBENG", "kelurahan" => "BARATAJAYA", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "GUBENG", "kelurahan" => "GUBENG", "kuota_awal" => 6, "kuota_sisa" => 5),
        // array("kecamatan" => "GUBENG", "kelurahan" => "KERTAJAYA", "kuota_awal" => 7, "kuota_sisa" => 6),
        // array("kecamatan" => "GUBENG", "kelurahan" => "MOJO", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "GUBENG", "kelurahan" => "PUCANG SEWU", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "GUNUNG ANYAR", "kelurahan" => "GUNUNG ANYAR", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "GUNUNG ANYAR", "kelurahan" => "GUNUNG ANYAR TAMBAK", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GUNUNG ANYAR", "kelurahan" => "RUNGKUT MENANGGAL", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "GUNUNG ANYAR", "kelurahan" => "RUNGKUT TENGAH", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "JAMBANGAN", "kelurahan" => "JAMBANGAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "JAMBANGAN", "kelurahan" => "KARAH", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "JAMBANGAN", "kelurahan" => "KEBONSARI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "JAMBANGAN", "kelurahan" => "PAGESANGAN", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "KARANG PILANG", "kelurahan" => "KARANG PILANG", "kuota_awal" => 7, "kuota_sisa" => 5),
        // array("kecamatan" => "KARANG PILANG", "kelurahan" => "KEBRAON", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "KARANG PILANG", "kelurahan" => "KEDURUS", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "KARANG PILANG", "kelurahan" => "WARU GUNUNG", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "KENJERAN", "kelurahan" => "BULAK BANTENG", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "KENJERAN", "kelurahan" => "SIDOTOPO WETAN", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "KENJERAN", "kelurahan" => "TAMBAK WEDI", "kuota_awal" => 2, "kuota_sisa" => 1),
        // array("kecamatan" => "KENJERAN", "kelurahan" => "TANAH KALI KEDINDING", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "KREMBANGAN", "kelurahan" => "DUPAK", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "KREMBANGAN", "kelurahan" => "KEMAYORAN", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "KREMBANGAN", "kelurahan" => "KREMBANGAN SELATAN", "kuota_awal" => 7, "kuota_sisa" => 7),
        // array("kecamatan" => "KREMBANGAN", "kelurahan" => "MOROKREMBANGAN", "kuota_awal" => 10, "kuota_sisa" => 10),
        // array("kecamatan" => "KREMBANGAN", "kelurahan" => "PERAK BARAT", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "BANGKINGAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "JERUK", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "LAKARSANTRI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "LIDAH KULON", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "LIDAH WETAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "LAKARSANTRI", "kelurahan" => "SUMURWELUT", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "DUKUH SUTOREJO", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "KALIJUDAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "KALISARI", "kuota_awal" => 5, "kuota_sisa" => 4),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "KEJAWAAN PUTIH TAMBAK", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "MANYAR SABRANGAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "MULYOREJO", "kelurahan" => "MULYOREJO", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "PABEAN CANTIAN", "kelurahan" => "BONGKARAN", "kuota_awal" => 7, "kuota_sisa" => 7),
        // array("kecamatan" => "PABEAN CANTIAN", "kelurahan" => "KREMBANGAN UTARA", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "PABEAN CANTIAN", "kelurahan" => "NYAMPLUNGAN", "kuota_awal" => 7, "kuota_sisa" => 5),
        // array("kecamatan" => "PABEAN CANTIAN", "kelurahan" => "TANJUNG PERAK", "kuota_awal" => 7, "kuota_sisa" => 6),
        // array("kecamatan" => "PAKAL", "kelurahan" => "BABAT JERAWAT", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "PAKAL", "kelurahan" => "BENOWO", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "PAKAL", "kelurahan" => "PAKAL", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "PAKAL", "kelurahan" => "SUMBER REJO", "kuota_awal" => 3, "kuota_sisa" => 2),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "KALIRUNGKUT", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "KEDUNG BARUK", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "MEDOKAN AYU", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "PENJARINGANSARI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "RUNGKUT KIDUL", "kuota_awal" => 2, "kuota_sisa" => 1),
        // array("kecamatan" => "RUNGKUT", "kelurahan" => "WONOREJO", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SAMBIKEREP", "kelurahan" => "BERINGIN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SAMBIKEREP", "kelurahan" => "LONTAR", "kuota_awal" => 12, "kuota_sisa" => 9),
        // array("kecamatan" => "SAMBIKEREP", "kelurahan" => "MADE", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "SAMBIKEREP", "kelurahan" => "SAMBIKEREP", "kuota_awal" => 6, "kuota_sisa" => 5),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "BANYU URIP", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "KUPANG KRAJAN", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "PAKIS", "kuota_awal" => 15, "kuota_sisa" => 8),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "PETEMON", "kuota_awal" => 5, "kuota_sisa" => 4),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "PUTAT JAYA", "kuota_awal" => 10, "kuota_sisa" => 5),
        // array("kecamatan" => "SAWAHAN", "kelurahan" => "SAWAHAN", "kuota_awal" => 10, "kuota_sisa" => 7),
        // array("kecamatan" => "SEMAMPIR", "kelurahan" => "AMPEL", "kuota_awal" => 8, "kuota_sisa" => 7),
        // array("kecamatan" => "SEMAMPIR", "kelurahan" => "PEGIRIAN", "kuota_awal" => 11, "kuota_sisa" => 8),
        // array("kecamatan" => "SEMAMPIR", "kelurahan" => "SIDOTOPO", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "SEMAMPIR", "kelurahan" => "UJUNG", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "SEMAMPIR", "kelurahan" => "WONOKUSUMO", "kuota_awal" => 11, "kuota_sisa" => 8),
        // array("kecamatan" => "SIMOKERTO", "kelurahan" => "KAPASAN", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "SIMOKERTO", "kelurahan" => "SIDODADI", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "SIMOKERTO", "kelurahan" => "SIMOKERTO", "kuota_awal" => 8, "kuota_sisa" => 7),
        // array("kecamatan" => "SIMOKERTO", "kelurahan" => "SIMOLAWANG", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "SIMOKERTO", "kelurahan" => "TAMBAKREJO", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "GEBANG PUTIH", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "KEPUTIH", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "KLAMPIS NGASEM", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "MEDOKAN SEMAMPIR", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "MENUR PUMPUNGAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "NGINDEN JANGKUNGAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SUKOLILO", "kelurahan" => "SEMOLOWARU", "kuota_awal" => 5, "kuota_sisa" => 3),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "PUTAT GEDE", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "SIMOMULYO", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "SIMOMULYO BARU", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "SONOKWIJENAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "SUKOMANUNGGAL", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "SUKOMANUNGGAL", "kelurahan" => "TANJUNGSARI", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "DUKUH SETRO", "kuota_awal" => 5, "kuota_sisa" => 2),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "GADING", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "KAPASMADYA BARU", "kuota_awal" => 9, "kuota_sisa" => 8),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "PACARKELING", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "PACARKEMBANG", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "PLOSO", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "RANGKAH", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "TAMBAKSARI", "kelurahan" => "TAMBAKSARI", "kuota_awal" => 8, "kuota_sisa" => 7),
        // array("kecamatan" => "TANDES", "kelurahan" => "BALONGSARI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "TANDES", "kelurahan" => "BANJAR SUGIHAN", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "TANDES", "kelurahan" => "KARANG POH", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "TANDES", "kelurahan" => "MANUKAN KULON", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "TANDES", "kelurahan" => "MANUKAN WETAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "TANDES", "kelurahan" => "TANDES", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "TEGALSARI", "kelurahan" => "DR. SOETOMO", "kuota_awal" => 4, "kuota_sisa" => 3),
        // array("kecamatan" => "TEGALSARI", "kelurahan" => "KEDUNGDORO", "kuota_awal" => 7, "kuota_sisa" => 7),
        // array("kecamatan" => "TEGALSARI", "kelurahan" => "KEPUTRAN", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "TEGALSARI", "kelurahan" => "TEGALSARI", "kuota_awal" => 8, "kuota_sisa" => 7),
        // array("kecamatan" => "TEGALSARI", "kelurahan" => "WONOREJO", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "TENGGILIS MEJOYO", "kelurahan" => "KENDANGSARI", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "TENGGILIS MEJOYO", "kelurahan" => "KUTISARI", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "TENGGILIS MEJOYO", "kelurahan" => "PANJANG JIWO", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "TENGGILIS MEJOYO", "kelurahan" => "TENGGILIS MEJOYO", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "WIYUNG", "kelurahan" => "BABATAN", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "WIYUNG", "kelurahan" => "BALAS KLUMPRIK", "kuota_awal" => 2, "kuota_sisa" => 2),
        // array("kecamatan" => "WIYUNG", "kelurahan" => "JAJAR TUNGGAL", "kuota_awal" => 1, "kuota_sisa" => 1),
        // array("kecamatan" => "WIYUNG", "kelurahan" => "WIYUNG", "kuota_awal" => 3, "kuota_sisa" => 2),
        // array("kecamatan" => "WONOCOLO", "kelurahan" => "BENDUL MERISI", "kuota_awal" => 6, "kuota_sisa" => 6),
        // array("kecamatan" => "WONOCOLO", "kelurahan" => "JEMUR WONOSARI", "kuota_awal" => 4, "kuota_sisa" => 4),
        // array("kecamatan" => "WONOCOLO", "kelurahan" => "MARGOREJO", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "WONOCOLO", "kelurahan" => "SIDOSERMO", "kuota_awal" => 10, "kuota_sisa" => 5),
        // array("kecamatan" => "WONOCOLO", "kelurahan" => "SIWALANKERTO", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "DARMO", "kuota_awal" => 5, "kuota_sisa" => 5),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "JAGIR", "kuota_awal" => 8, "kuota_sisa" => 7),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "NGAGEL", "kuota_awal" => 3, "kuota_sisa" => 3),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "NGAGEL REJO", "kuota_awal" => 8, "kuota_sisa" => 8),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "SAWUNGGALING", "kuota_awal" => 9, "kuota_sisa" => 8),
        // array("kecamatan" => "WONOKROMO", "kelurahan" => "WONOKROMO", "kuota_awal" => 5, "kuota_sisa" => 5)
        array("id"=>52,"kuota_awal" => 0, "kuota_sisa" => 0),
        array("id"=>153, "kuota_awal" => 7, "kuota_sisa" => 0),
        array("id"=>149,"kuota_awal" => 10, "kuota_sisa" => 0),
        array("id"=>152,"kuota_awal" => 12, "kuota_sisa" => 0),
        array("id"=>151,"kuota_awal" =>11, "kuota_sisa" => 0)
    );

    public function run()
    {
            foreach ($this->updates as $key => $value) {
                $kuotas=KuotaKelurahan::findOrFail($value['id']);
                $kuotas->save();
                // $user=User::whereId($value['id'])->update(['password'=>$value['password']]);
            }
    }
}
