<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UserKelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public $users = array(
        array("name" => "BETA RAMADHANI, M.Sc|LONTAR|SAMBIKEREP", "username" => "kel_lontar", "password_text" => "@lontar2023", "password" => "@lontar2023"),
        array("name" => "SITI NURUL HANIFAH, S.Sos|KALIJUDAN|MULYOREJO", "username" => "kel_kalijudan", "password_text" => "123456", "password" => "123456"),
        array("name" => "R. TRI KOESFEDI JOES HARDIANTO, ST|SUKOLILO BARU|BULAK", "username" => "kel_sukolilobaru", "password_text" => "123456", "password" => "123456"),
        array("name" => "LPMK DARMO|DARMO|WONOKROMO", "username" => "lpmk_darmo", "password_text" => "130570", "password" => "130570"),
        array("name" => "MOHAMMAD ZUL CHAIDIR, S.ST, M.M.|SIDOSERMO|WONOCOLO", "username" => "kel_sidosermo", "password_text" => "2022@sidos", "password" => "2022@sidos"),
        array("name" => "LPMK DUKUH SUTOREJO|DUKUH SUTOREJO|MULYOREJO", "username" => "lpmk_dukuhsutorejo", "password_text" => "357826", "password" => "357826"),
        array("name" => "EVI ANDRIANI, SH|AIRLANGGA|GUBENG", "username" => "kel_airlangga", "password_text" => "airla2017", "password" => "airla2017"),
        array("name" => "MOCHAMAD IMZAK, S.Sos|AMPEL|SEMAMPIR", "username" => "kel_ampel", "password_text" => "ampel2017", "password" => "ampel2017"),
        array("name" => "ILHAM SAMPURNO, SH, M.Si|ASEM ROWO|ASEM ROWO", "username" => "kel_asemrowo", "password_text" => "asemr2017", "password" => "asemr2017"),
        array("name" => "HERTIKA VITRA HENING, SH, M.Si|BABATAN|WIYUNG", "username" => "kel_babatan", "password_text" => "babat2017", "password" => "babat2017"),
        array("name" => "DARMAWAN, S.Sos, M.Si|BABAT JERAWAT|PAKAL", "username" => "kel_babatjerawat", "password_text" => "babatjerawat1234", "password" => "babatjerawat1234"),
        array("name" => "LULUK TRI KRISMAWATI SE  |BALAS KLUMPRIK|WIYUNG", "username" => "kel_balasklumprik", "password_text" => "balas2017", "password" => "balas2017"),
        array("name" => "MINARNI, ST|BALONGSARI|TANDES", "username" => "kel_balongsari", "password_text" => "balon2017", "password" => "balon2017"),
        array("name" => "DYAH LISTYORINI, S.Psi.|BANGKINGAN|LAKARSANTRI", "username" => "kel_bangkingan", "password_text" => "bangk2017", "password" => "bangk2017"),
        array("name" => "GANI NURCAHYONO SH|BANJAR SUGIHAN|TANDES", "username" => "kel_banjarsugihan", "password_text" => "banja2017", "password" => "banja2017"),
        array("name" => "DEDY AHMAD CHOIRUDDIN ST|BANYU URIP|SAWAHAN", "username" => "kel_banyuurip", "password_text" => "banyu2017", "password" => "banyu2017"),
        array("name" => "ENTIK LINDASARI, SE|BARATAJAYA|GUBENG", "username" => "kel_baratajaya", "password_text" => "barat2017", "password" => "barat2017"),
        array("name" => "YUDHI PRIYO UTOMO, S.Sos |BULAK BANTENG|KENJERAN", "username" => "kel_bulakbanteng", "password_text" => "bb12345*", "password" => "bb12345*"),
        array("name" => "RULLY PRASETYA NEGARA, S.STP, M.Si|BENDUL MERISI|WONOCOLO", "username" => "kel_bendulmerisi", "password_text" => "bendul_23", "password" => "bendul_23"),
        array("name" => "Drs. MUSTOFA KHOLIL, M.Si|BENOWO|PAKAL", "username" => "kel_benowo", "password_text" => "benowo2017", "password" => "benowo2017"),
        array("name" => "EDI RUPONO SH|BONGKARAN|PABEAN CANTIAN", "username" => "kel_bongkaran", "password_text" => "bongk2017", "password" => "bongk2017"),
        array("name" => "PUPUT PUJIASTUTI, S.STP|BERINGIN|SAMBIKEREP", "username" => "kel_bringin", "password_text" => "bring2017", "password" => "bring2017"),
        array("name" => "ISWAN ARIF, S.T.|BUBUTAN|BUBUTAN", "username" => "kel_bubutan", "password_text" => "bubut2017", "password" => "bubut2017"),
        array("name" => "GLORIA PUSPA CENDANA, S.STP, M.A|BULAK|BULAK", "username" => "kel_bulak", "password_text" => "bulak1107", "password" => "bulak1107"),
        array("name" => "SUGENG HARIJONO, SH, MH|DARMO|WONOKROMO", "username" => "kel_darmo", "password_text" => "darmo2017", "password" => "darmo2017"),
        array("name" => "NUR RATNA WULAN KARTINI PANCAWARDANI, S.Sos|DR. SOETOMO|TEGALSARI", "username" => "kel_dr.sutomo", "password_text" => "dr.su2017", "password" => "dr.su2017"),
        array("name" => "AHRUL FAHZIAR, S.H|DUKUH SETRO|TAMBAKSARI", "username" => "kel_dukuhsetro", "password_text" => "dukuh2017", "password" => "dukuh2017"),
        array("name" => "NURUL AZIZAH, SE|DUKUH MENANGGAL|GAYUNGAN", "username" => "kel_dukuhmenanggal", "password_text" => "dukuh2017", "password" => "dukuh2017"),
        array("name" => "FAHMI FITRA ARDIANSJAH, S.STP|DUKUH KUPANG|DUKUH PAKIS", "username" => "kel_dukuhkupang", "password_text" => "dukuh2017", "password" => "dukuh2017"),
        array("name" => "ANDREAS SURYAWAN, S.STP|DUKUH PAKIS|DUKUH PAKIS", "username" => "kel_dukuhpakis", "password_text" => "dukuh2017", "password" => "dukuh2017"),
        array("name" => "ISWORO ANDIK SUCAHYO, ST|DUKUH SUTOREJO|MULYOREJO", "username" => "kel_dukuhsutorejo", "password_text" => "dukuh2017", "password" => "dukuh2017"),
        array("name" => "LUTFAN ADIE WIBOWO, S.STP|DUPAK|KREMBANGAN", "username" => "kel_dupak", "password_text" => "dupak2017", "password" => "dupak2017"),
        array("name" => "SUNARDI, SE|EMBONG KALIASIN|GENTENG", "username" => "kel_embongkaliasin", "password_text" => "embon2017", "password" => "embon2017"),
        array("name" => "LPMK KALIJUDAN|KALIJUDAN|MULYOREJO", "username" => "lpmk_kalijudan", "password_text" => "end301094", "password" => "end301094"),
        array("name" => "ANGGORO NOEVIANTO, SH|SIDOTOPO|SEMAMPIR", "username" => "kel_sidotopo", "password_text" => "g@mis2022", "password" => "g@mis2022"),
        array("name" => "EFRAN PRIAMBODO, S.Sos|GADING|TAMBAKSARI", "username" => "kel_gading", "password_text" => "gading2017", "password" => "gading2017"),
        array("name" => "INDRIYANI SETIYAWATI, S.Sos|GEBANG PUTIH|SUKOLILO", "username" => "kel_gebangputih", "password_text" => "geban2017", "password" => "geban2017"),
        array("name" => "KARLINA WINARYANTI, SE|GENTENG|GENTENG", "username" => "kel_genteng", "password_text" => "gente2017", "password" => "gente2017"),
        array("name" => "BUANG EKA BAKHTIAR, SP|GENTING KALIANAK|ASEM ROWO", "username" => "kel_gentingkalianak", "password_text" => "genti2017", "password" => "genti2017"),
        array("name" => "SRI RETNO TJATUR WAHJUNI S.Sos, MM|GUBENG|GUBENG", "username" => "kel_gubeng", "password_text" => "guben2017", "password" => "guben2017"),
        array("name" => "CHRISTIONO, SH, M.Si|GUNDIH|BUBUTAN", "username" => "kel_gundih", "password_text" => "gundi2017", "password" => "gundi2017"),
        array("name" => "SITI SALMAH A.Md|GUNUNG SARI|DUKUH PAKIS", "username" => "kel_gunungsari", "password_text" => "gunun2017", "password" => "gunun2017"),
        array("name" => "DAGLISH YULIYANTORO, S.T.|GUNUNG ANYAR|GUNUNG ANYAR", "username" => "kel_gununganyar", "password_text" => "gunun2017", "password" => "gunun2017"),
        array("name" => "DONNY ARDYAN, ST|GUNUNG ANYAR TAMBAK|GUNUNG ANYAR", "username" => "kel_gununganyartambak", "password_text" => "gunun2017", "password" => "gunun2017"),
        array("name" => "perak utara|PERAK UTARA|PABEAN CANTIAN", "username" => "kel_perakutara", "password_text" => "hariokokakes", "password" => "hariokokakes"),
        array("name" => "ACHMAD FIDA FAJAR FEBRIANSYAH, S.H.|KEPUTIH|SUKOLILO", "username" => "kel_keputih", "password_text" => "itaqwat1", "password" => "itaqwat1"),
        array("name" => "LAKSMI SUPROBORINI, ST, M.M.T.|JAGIR|WONOKROMO", "username" => "kel_jagir", "password_text" => "jagir2017", "password" => "jagir2017"),
        array("name" => "YONO, SE, MM|JAJAR TUNGGAL|WIYUNG", "username" => "kel_jajartunggal", "password_text" => "jajar2017", "password" => "jajar2017"),
        array("name" => "SANNY NOERMA SAFAAH, ST|JAMBANGAN|JAMBANGAN", "username" => "kel_jambangan", "password_text" => "jamba2017", "password" => "jamba2017"),
        array("name" => "MOHAMAD  YASIN, SH|JEMUR WONOSARI|WONOCOLO", "username" => "kel_jemurwonosari", "password_text" => "jemur2017", "password" => "jemur2017"),
        array("name" => "TIENA WAHJUNINGSIH PRIBADI, SH, M.Hum|JEPARA|BUBUTAN", "username" => "kel_jepara", "password_text" => "jepar2017", "password" => "jepar2017"),
        array("name" => "MISGIONO ST|JERUK|LAKARSANTRI", "username" => "kel_jeruk", "password_text" => "jeruk2017", "password" => "jeruk2017"),
        array("name" => "AHMAD RIDHO ANSHORI, S.STP|KALIRUNGKUT|RUNGKUT", "username" => "kel_kalirungkut", "password_text" => "kalir2017", "password" => "kalir2017"),
        array("name" => "YUDIONO, S.T., M.T.|KALISARI|MULYOREJO", "username" => "kel_kalisari", "password_text" => "kalis2017", "password" => "kalis2017"),
        array("name" => "ARIS KHRESNAMUKTI S.STP, M.Si|KANDANGAN|BENOWO", "username" => "kel_kandangan", "password_text" => "kanda2017", "password" => "kanda2017"),
        array("name" => "DJOKO TRI MULYONO, S.T.|KAPASMADYA BARU|TAMBAKSARI", "username" => "kel_kapasmadyabaru", "password_text" => "kapas2017", "password" => "kapas2017"),
        array("name" => "MOCHAMAD ADHARI, S.H|KAPASAN|SIMOKERTO", "username" => "kel_kapasan", "password_text" => "kapas2017", "password" => "kapas2017"),
        array("name" => "RIDZOTULLAHMAD NURCHAKIM, S.Gz, M.PSDM.|KAPASARI|GENTENG", "username" => "kel_kapasari", "password_text" => "kapas2017", "password" => "kapas2017"),
        array("name" => "KRISNA DWI HARYADI, S.E.|KARAH|JAMBANGAN", "username" => "kel_karah", "password_text" => "karah2017", "password" => "karah2017"),
        array("name" => "DJATMIKA OETAMA, SH|KARANG POH|TANDES", "username" => "kel_karangpoh", "password_text" => "karan2017", "password" => "karan2017"),
        array("name" => "SETIYA IRAMA NINGSIH SH,MM|KARANG PILANG|KARANG PILANG", "username" => "kel_karangpilang", "password_text" => "karpil_10", "password" => "karpil_10"),
        array("name" => "RERRY SETIANINGTIYASWATI S.H.|KEBONSARI|JAMBANGAN", "username" => "kel_kebonsari", "password_text" => "kebonsari2019", "password" => "kebonsari2019"),
        array("name" => "MUALIM SE|KEBRAON|KARANG PILANG", "username" => "kel_kebraon", "password_text" => "kebra2017", "password" => "kebra2017"),
        array("name" => "FATIN HAMAMAH, S.Ag.|KEDUNG BARUK|RUNGKUT", "username" => "kel_kedungbaruk", "password_text" => "kedun2017", "password" => "kedun2017"),
        array("name" => "AYU VITASARI SP, M.Agr|KEDUNG COWEK|BULAK", "username" => "kel_kedungcowek", "password_text" => "kedun2017", "password" => "kedun2017"),
        array("name" => "MOCH. ALI TAUFIQ, S.E.|KEDUNGDORO|TEGALSARI", "username" => "kel_kedungdoro", "password_text" => "kedun2017", "password" => "kedun2017"),
        array("name" => "WISNU PURWOWIYONO, S.Sos|KEDURUS|KARANG PILANG", "username" => "kel_kedurus", "password_text" => "kedur2017", "password" => "kedur2017"),
        array("name" => "SETIA KUSTANTO, SH|KEJAWAAN PUTIH TAMBAK|MULYOREJO", "username" => "kel_kejawanputihtambak", "password_text" => "kejaw2017", "password" => "kejaw2017"),
        array("name" => "WAHYUDI HARDIYANTOI, S.Sos|UJUNG|SEMAMPIR", "username" => "kel_ujung", "password_text" => "kelurahanujung1945@gmail.com", "password" => "kelurahanujung1945@gmail.com"),
        array("name" => "ARIEF WITJAKSANA, S.Sos, M.Si|KEMAYORAN|KREMBANGAN", "username" => "kel_kemayoran", "password_text" => "kemaya2017", "password" => "kemaya2017"),
        array("name" => "WISNU WIBOWO, ST, M.I.Kom|KENDANGSARI|TENGGILIS MEJOYO", "username" => "kel_kendangsari", "password_text" => "kenda2017", "password" => "kenda2017"),
        array("name" => "ANIS PUDJI ASTUTIK S.Sos|KENJERAN|BULAK", "username" => "kel_kenjeran", "password_text" => "kenje2017", "password" => "kenje2017"),
        array("name" => "DRS. KARTIKA INDRAYANA|KEPUTRAN|TEGALSARI", "username" => "kel_keputran", "password_text" => "keput2017", "password" => "keput2017"),
        array("name" => "BRAM BENNITO, ST, M.Si|WONOKUSUMO|SEMAMPIR", "username" => "kel_wonokusumo", "password_text" => "kesra@2017", "password" => "kesra@2017"),
        array("name" => "DOMY WAHYU NUGROHO, S.STP, M.PSDM.|KETABANG|GENTENG", "username" => "kel_ketabang", "password_text" => "ketab2017", "password" => "ketab2017"),
        array("name" => "M. HANANG PRASETYO ADI, S.H.|KETINTANG|GAYUNGAN", "username" => "kel_ketintang", "password_text" => "ketin@2022", "password" => "ketin@2022"),
        array("name" => "MOHAMMAD FAJAR FANANI, S.H.|KLAMPIS NGASEM|SUKOLILO", "username" => "kel_klampisngasem", "password_text" => "klamp2017", "password" => "klamp2017"),
        array("name" => "ABDUS SHOMAD, S.Sos|KREMBANGAN UTARA|PABEAN CANTIAN", "username" => "kel_krembanganutara", "password_text" => "kremb2017", "password" => "kremb2017"),
        array("name" => "SUMADALANA S.Sos|KREMBANGAN SELATAN|KREMBANGAN", "username" => "kel_krembanganselatan", "password_text" => "kremb2017", "password" => "kremb2017"),
        array("name" => "SUWITOYUSWO, S.Sos, MM|LIDAH KULON|LAKARSANTRI", "username" => "kel_lidahkulon", "password_text" => "kulon2017", "password" => "kulon2017"),
        array("name" => "HERMAN FELANI, ST|KUPANG KRAJAN|SAWAHAN", "username" => "kel_kupangkrajan", "password_text" => "kupan2017", "password" => "kupan2017"),
        array("name" => "GALUH META INDARWATI, S.STP|KUTISARI|TENGGILIS MEJOYO", "username" => "kel_kutisari", "password_text" => "Kutos2017", "password" => "Kutos2017"),
        array("name" => "Dra. SRI HERYANTI TRISUWANDANI, MM|LAKARSANTRI|LAKARSANTRI", "username" => "kel_lakarsantri", "password_text" => "lakar2017", "password" => "lakar2017"),
        array("name" => "ANDRI KURNIAWAN, S.STP, M.Si|LIDAH WETAN|LAKARSANTRI", "username" => "kel_lidahwetan", "password_text" => "lidah2017", "password" => "lidah2017"),
        array("name" => "LPMK NYAMPLUNGAN|NYAMPLUNGAN|PABEAN CANTIAN", "username" => "lpmk_nyamplungan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK DUKUH SETRO|DUKUH SETRO|TAMBAKSARI", "username" => "lpmk_dukuhsetro", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIMOKERTO|SIMOKERTO|SIMOKERTO", "username" => "lpmk_simokerto", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEBONSARI|KEBONSARI|JAMBANGAN", "username" => "lpmk_kebonsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BANJAR SUGIHAN|BANJAR SUGIHAN|TANDES", "username" => "lpmk_banjarsugihan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PEGIRIAN|PEGIRIAN|SEMAMPIR", "username" => "lpmk_pegirian", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK RUNGKUT KIDUL|RUNGKUT KIDUL|RUNGKUT", "username" => "lpmk_rungkutkidul", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEMAYORAN|KEMAYORAN|KREMBANGAN", "username" => "lpmk_kemayoran", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GUNDIH|GUNDIH|BUBUTAN", "username" => "lpmk_gundih", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BULAK|BULAK|BULAK", "username" => "lpmk_bulak", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIMOMULYO BARU|SIMOMULYO BARU|SUKOMANUNGGAL", "username" => "lpmk_simomulyobaru", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SAWAHAN|SAWAHAN|SAWAHAN", "username" => "lpmk_sawahan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEDUNG COWEK|KEDUNG COWEK|BULAK", "username" => "lpmk_kedungcowek", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SAWUNGGALING|SAWUNGGALING|WONOKROMO", "username" => "lpmk_sawunggaling", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEPUTRAN|KEPUTRAN|TEGALSARI", "username" => "lpmk_keputran", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIMOMULYO|SIMOMULYO|SUKOMANUNGGAL", "username" => "lpmk_simomulyo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK WONOKUSUMO|WONOKUSUMO|SEMAMPIR", "username" => "lpmk_wonokusumo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SEMEMI|SEMEMI|BENOWO", "username" => "lpmk_sememi", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK EMBONG KALIASIN|EMBONG KALIASIN|GENTENG", "username" => "lpmk_embongkaliasin", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BALONGSARI|BALONGSARI|TANDES", "username" => "lpmk_balongsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SEMOLOWARU|SEMOLOWARU|SUKOLILO", "username" => "lpmk_semolowaru", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SONOKWIJENAN|SONOKWIJENAN|SUKOMANUNGGAL", "username" => "lpmk_sonokwijenan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK UJUNG|UJUNG|SEMAMPIR", "username" => "lpmk_ujung", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK RUNGKUT MENANGGAL|RUNGKUT MENANGGAL|GUNUNG ANYAR", "username" => "lpmk_rungkutmenanggal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PUCANG SEWU|PUCANG SEWU|GUBENG", "username" => "lpmk_pucangsewu", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BABAT JERAWAT|BABAT JERAWAT|PAKAL", "username" => "lpmk_babatjerawat", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK ASEM ROWO|ASEM ROWO|ASEM ROWO", "username" => "lpmk_asemrowo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GADING|GADING|TAMBAKSARI", "username" => "lpmk_gading", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KENDANGSARI|KENDANGSARI|TENGGILIS MEJOYO", "username" => "lpmk_kendangsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KAPASAN|KAPASAN|SIMOKERTO", "username" => "lpmk_kapasan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MOROKREMBANGAN|MOROKREMBANGAN|KREMBANGAN", "username" => "lpmk_morokrembangan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BONGKARAN|BONGKARAN|PABEAN CANTIAN", "username" => "lpmk_bongkaran", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIDOTOPO|SIDOTOPO|SEMAMPIR", "username" => "lpmk_sidotopo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK NGAGEL REJO|NGAGEL REJO|WONOKROMO", "username" => "lpmk_ngagelrejo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIDODADI|SIDODADI|SIMOKERTO", "username" => "lpmk_sidodadi", "password_text" => "Lpmk2021", "password" => "Lpmk2021"),
        array("name" => "LPMK MENUR PUMPUNGAN|MENUR PUMPUNGAN|SUKOLILO", "username" => "lpmk_menurpumpungan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PLOSO|PLOSO|TAMBAKSARI", "username" => "lpmk_ploso", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PACARKEMBANG|PACARKEMBANG|TAMBAKSARI", "username" => "lpmk_pacarkembang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TAMBAK SARIOSO|TAMBAK SARIOSO|ASEM ROWO", "username" => "lpmk_tambaksarioso", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TAMBAK OSO WILANGUN|TAMBAK OSO WILANGUN|BENOWO", "username" => "lpmk_tambakosowilangun", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BENDUL MERISI|BENDUL MERISI|WONOCOLO", "username" => "lpmk_bendulmerisi", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK DUKUH KUPANG|DUKUH KUPANG|DUKUH PAKIS", "username" => "lpmk_dukuhkupang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MANUKAN KULON|MANUKAN KULON|TANDES", "username" => "lpmk_manukankulon", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK AIRLANGGA|AIRLANGGA|GUBENG", "username" => "lpmk_airlangga", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PENELEH|PENELEH|GENTENG", "username" => "lpmk_peneleh", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK NGINDEN JANGKUNGAN|NGINDEN JANGKUNGAN|SUKOLILO", "username" => "lpmk_ngindenjangkungan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GUNUNG SARI|GUNUNG SARI|DUKUH PAKIS", "username" => "lpmk_gunungsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SUKOLILO BARU|SUKOLILO BARU|BULAK", "username" => "lpmk_sukolilobaru", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KETABANG|KETABANG|GENTENG", "username" => "lpmk_ketabang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIDOSERMO|SIDOSERMO|WONOCOLO", "username" => "lpmk_sidosermo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEDUNG BARUK|KEDUNG BARUK|RUNGKUT", "username" => "lpmk_kedungbaruk", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK JEPARA|JEPARA|BUBUTAN", "username" => "lpmk_jepara", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KLAMPIS NGASEM|KLAMPIS NGASEM|SUKOLILO", "username" => "lpmk_klampisngasem", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MEDOKAN SEMAMPIR|MEDOKAN SEMAMPIR|SUKOLILO", "username" => "lpmk_medokansemampir", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PAKIS|PAKIS|SAWAHAN", "username" => "lpmk_pakis", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BARATAJAYA|BARATAJAYA|GUBENG", "username" => "lpmk_baratajaya", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIWALANKERTO|SIWALANKERTO|WONOCOLO", "username" => "lpmk_siwalankerto", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KERTAJAYA|KERTAJAYA|GUBENG", "username" => "lpmk_kertajaya", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TEMBOK DUKUH|TEMBOK DUKUH|BUBUTAN", "username" => "lpmk_tembokdukuh", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KARANG PILANG|KARANG PILANG|KARANG PILANG", "username" => "lpmk_karangpilang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GUNUNG ANYAR|GUNUNG ANYAR|GUNUNG ANYAR", "username" => "lpmk_gununganyar", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEBRAON|KEBRAON|KARANG PILANG", "username" => "lpmk_kebraon", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK WARU GUNUNG|WARU GUNUNG|KARANG PILANG", "username" => "lpmk_warugunung", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PAGESANGAN|PAGESANGAN|JAMBANGAN", "username" => "lpmk_pagesangan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TANDES|TANDES|TANDES", "username" => "lpmk_tandes", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TAMBAK WEDI|TAMBAK WEDI|KENJERAN", "username" => "lpmk_tambakwedi", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK JAJAR TUNGGAL|JAJAR TUNGGAL|WIYUNG", "username" => "lpmk_jajartunggal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GENTENG|GENTENG|GENTENG", "username" => "lpmk_genteng", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEDURUS|KEDURUS|KARANG PILANG", "username" => "lpmk_kedurus", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GAYUNGAN|GAYUNGAN|GAYUNGAN", "username" => "lpmk_gayungan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK DUKUH MENANGGAL|DUKUH MENANGGAL|GAYUNGAN", "username" => "lpmk_dukuhmenanggal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KARAH|KARAH|JAMBANGAN", "username" => "lpmk_karah", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MENANGGAL|MENANGGAL|GAYUNGAN", "username" => "lpmk_menanggal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PERAK TIMUR|PERAK TIMUR|PABEAN CANTIAN", "username" => "lpmk_peraktimur", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KETINTANG|KETINTANG|GAYUNGAN", "username" => "lpmk_ketintang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KAPASMADYA BARU|KAPASMADYA BARU|TAMBAKSARI", "username" => "lpmk_kapasmadyabaru", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MANUKAN WETAN|MANUKAN WETAN|TANDES", "username" => "lpmk_manukanwetan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PAKAL|PAKAL|PAKAL", "username" => "lpmk_pakal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK RUNGKUT TENGAH|RUNGKUT TENGAH|GUNUNG ANYAR", "username" => "lpmk_rungkuttengah", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BENOWO|BENOWO|PAKAL", "username" => "lpmk_benowo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK LONTAR|LONTAR|SAMBIKEREP", "username" => "lpmk_lontar", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PACARKELING|PACARKELING|TAMBAKSARI", "username" => "lpmk_pacarkeling", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK JERUK|JERUK|LAKARSANTRI", "username" => "lpmk_jeruk", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TEGALSARI|TEGALSARI|TEGALSARI", "username" => "lpmk_tegalsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KALISARI|KALISARI|MULYOREJO", "username" => "lpmk_kalisari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TANJUNGSARI|TANJUNGSARI|SUKOMANUNGGAL", "username" => "lpmk_tanjungsari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GEBANG PUTIH|GEBANG PUTIH|SUKOLILO", "username" => "lpmk_gebangputih", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MULYOREJO|MULYOREJO|MULYOREJO", "username" => "lpmk_mulyorejo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PRADAH KALIKENDAL|PRADAH KALIKENDAL|DUKUH PAKIS", "username" => "lpmk_pradahkalikendal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIMOLAWANG|SIMOLAWANG|SIMOKERTO", "username" => "lpmk_simolawang", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK LIDAH WETAN|LIDAH WETAN|LAKARSANTRI", "username" => "lpmk_lidahwetan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BALAS KLUMPRIK|BALAS KLUMPRIK|WIYUNG", "username" => "lpmk_balasklumprik", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SUMURWELUT|SUMURWELUT|LAKARSANTRI", "username" => "lpmk_sumurwelut", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEDUNGDORO|KEDUNGDORO|TEGALSARI", "username" => "lpmk_kedungdoro", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SUKOMANUNGGAL|SUKOMANUNGGAL|SUKOMANUNGGAL", "username" => "lpmk_sukomanunggal", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK RANGKAH|RANGKAH|TAMBAKSARI", "username" => "lpmk_rangkah", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MANYAR SABRANGAN|MANYAR SABRANGAN|MULYOREJO", "username" => "lpmk_manyarsabrangan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SAMBIKEREP|SAMBIKEREP|SAMBIKEREP", "username" => "lpmk_sambikerep", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK ROMOKALISARI|ROMOKALISARI|BENOWO", "username" => "lpmk_romokalisari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BANGKINGAN|BANGKINGAN|LAKARSANTRI", "username" => "lpmk_bangkingan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BABATAN|BABATAN|WIYUNG", "username" => "lpmk_babatan", "password_text" => "Lpmk2021", "password" => "Lpmk2021"),
        array("name" => "LPMK PERAK BARAT|PERAK BARAT|KREMBANGAN", "username" => "lpmk_perakbarat", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MARGOREJO|MARGOREJO|WONOCOLO", "username" => "lpmk_margorejo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KREMBANGAN UTARA|KREMBANGAN UTARA|PABEAN CANTIAN", "username" => "lpmk_krembanganutara", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MADE|MADE|SAMBIKEREP", "username" => "lpmk_made", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KALIRUNGKUT|KALIRUNGKUT|RUNGKUT", "username" => "lpmk_kalirungkut", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KUTISARI|KUTISARI|TENGGILIS MEJOYO", "username" => "lpmk_kutisari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TANJUNG PERAK|TANJUNG PERAK|PABEAN CANTIAN", "username" => "lpmk_tanjungperak", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PETEMON|PETEMON|SAWAHAN", "username" => "lpmk_petemon", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK JEMUR WONOSARI|JEMUR WONOSARI|WONOCOLO", "username" => "lpmk_jemurwonosari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK LAKARSANTRI|LAKARSANTRI|LAKARSANTRI", "username" => "lpmk_lakarsantri", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BANYU URIP|BANYU URIP|SAWAHAN", "username" => "lpmk_banyuurip", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GENTING KALIANAK|GENTING KALIANAK|ASEM ROWO", "username" => "lpmk_gentingkalianak", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK DUKUH PAKIS|DUKUH PAKIS|DUKUH PAKIS", "username" => "lpmk_dukuhpakis", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK AMPEL|AMPEL|SEMAMPIR", "username" => "lpmk_ampel", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KANDANGAN|KANDANGAN|BENOWO", "username" => "lpmk_kandangan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KENJERAN|KENJERAN|BULAK", "username" => "lpmk_kenjeran", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK WIYUNG|WIYUNG|WIYUNG", "username" => "lpmk_wiyung", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KEPUTIH|KEPUTIH|SUKOLILO", "username" => "lpmk_keputih", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KUPANG KRAJAN|KUPANG KRAJAN|SAWAHAN", "username" => "lpmk_kupangkrajan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SUMBER REJO|SUMBER REJO|PAKAL", "username" => "lpmk_sumberrejo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BULAK BANTENG|BULAK BANTENG|KENJERAN", "username" => "lpmk_bulakbanteng", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KAPASARI|KAPASARI|GENTENG", "username" => "lpmk_kapasari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PUTAT JAYA|PUTAT JAYA|SAWAHAN", "username" => "lpmk_putatjaya", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK GUNUNG ANYAR TAMBAK|GUNUNG ANYAR TAMBAK|GUNUNG ANYAR", "username" => "lpmk_gununganyartambak", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK DUPAK|DUPAK|KREMBANGAN", "username" => "lpmk_dupak", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK BUBUTAN|BUBUTAN|BUBUTAN", "username" => "lpmk_bubutan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK JAMBANGAN|JAMBANGAN|JAMBANGAN", "username" => "lpmk_jambangan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PANJANG JIWO|PANJANG JIWO|TENGGILIS MEJOYO", "username" => "lpmk_panjangjiwo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK LIDAH KULON|LIDAH KULON|LAKARSANTRI", "username" => "lpmk_lidahkulon", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TANAH KALI KEDINDING|TANAH KALI KEDINDING|KENJERAN", "username" => "lpmk_tanahkalikedinding", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MOJO|MOJO|GUBENG", "username" => "lpmk_mojo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PENJARINGANSARI|PENJARINGANSARI|RUNGKUT", "username" => "lpmk_penjaringansari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK MEDOKAN AYU|MEDOKAN AYU|RUNGKUT", "username" => "lpmk_medokanayu", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK KARANG POH|KARANG POH|TANDES", "username" => "lpmk_karangpoh", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK WONOKROMO|WONOKROMO|WONOKROMO", "username" => "lpmk_wonokromo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TAMBAKSARI|TAMBAKSARI|TAMBAKSARI", "username" => "lpmk_tambaksari", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK PUTAT GEDE|PUTAT GEDE|SUKOMANUNGGAL", "username" => "lpmk_putatgede", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK SIDOTOPO WETAN|SIDOTOPO WETAN|KENJERAN", "username" => "lpmk_sidotopowetan", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK TENGGILIS MEJOYO|TENGGILIS MEJOYO|TENGGILIS MEJOYO", "username" => "lpmk_tenggilismejoyo", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "LPMK NGAGEL|NGAGEL|WONOKROMO", "username" => "lpmk_ngagel", "password_text" => "lpmk2021", "password" => "lpmk2021"),
        array("name" => "Dra. RETNA YULIASTRI|MANUKAN KULON|TANDES", "username" => "kel_manukankulon", "password_text" => "manuk2017", "password" => "manuk2017"),
        array("name" => "Drs. DIDIET BUDHI PUTRANTO, M.Si|MANUKAN WETAN|TANDES", "username" => "kel_manukanwetan", "password_text" => "manuk2017", "password" => "manuk2017"),
        array("name" => "RONNY NOVIANTO SE, SH, M.H|MANYAR SABRANGAN|MULYOREJO", "username" => "kel_manyarsabrangan", "password_text" => "manya2017", "password" => "manya2017"),
        array("name" => "RURY DAMAYANTI, SH, MH|MARGOREJO|WONOCOLO", "username" => "kel_margorejo", "password_text" => "margo2017", "password" => "margo2017"),
        array("name" => "LPMK KREMBANGAN SELATAN|KREMBANGAN SELATAN|KREMBANGAN", "username" => "lpmk_krembanganselatan", "password_text" => "marjo758099", "password" => "marjo758099"),
        array("name" => "ZAINUL ABIDIN S.Sos|MEDOKAN AYU|RUNGKUT", "username" => "kel_medokanayu", "password_text" => "medok2017", "password" => "medok2017"),
        array("name" => "TAUFAN SETIAWAN, A.Md|MENANGGAL|GAYUNGAN", "username" => "kel_menanggal", "password_text" => "menan2017", "password" => "menan2017"),
        array("name" => "ALI PRANOTO, SKM, M.Kes.|MENUR PUMPUNGAN|SUKOLILO", "username" => "kel_menurpumpungan", "password_text" => "menur2017", "password" => "menur2017"),
        array("name" => "Drs. HARUN ISMAIL, MM|MOROKREMBANGAN|KREMBANGAN", "username" => "kel_morokrembangan", "password_text" => "morok2017", "password" => "morok2017"),
        array("name" => "Dra. KATHARINA EVI WAHJUNI, MM|MOJO|GUBENG", "username" => "kel_mojo", "password_text" => "motogp46", "password" => "motogp46"),
        array("name" => "ENY NUROTUL KHOTIMAH, ST|MULYOREJO|MULYOREJO", "username" => "kel_mulyorejo", "password_text" => "mulyo2017", "password" => "mulyo2017"),
        array("name" => "LILIK SURYANI|NGAGEL|WONOKROMO", "username" => "kel_ngagel", "password_text" => "ngage2017", "password" => "ngage2017"),
        array("name" => "CUT WULANDARI DIAN A., S.Psi, M.Si|NGAGEL REJO|WONOKROMO", "username" => "kel_ngagelrejo", "password_text" => "ngagelrejoadm", "password" => "ngagelrejoadm"),
        array("name" => "NOVY ASTIWIE SH|NGINDEN JANGKUNGAN|SUKOLILO", "username" => "kel_ngindenjangkungan", "password_text" => "ngind2017", "password" => "ngind2017"),
        array("name" => "ESTU SULAKSONO, SH|NYAMPLUNGAN|PABEAN CANTIAN", "username" => "kel_nyamplungan", "password_text" => "nyampl123", "password" => "nyampl123"),
        array("name" => "MOHAMMAD HASAN ARIEF, ST|PACARKEMBANG|TAMBAKSARI", "username" => "kel_pacarkembang", "password_text" => "pacar2017", "password" => "pacar2017"),
        array("name" => "ENY KURNIAWATI, S.STP, M.Si|PACARKELING|TAMBAKSARI", "username" => "kel_pacarkeling", "password_text" => "pacar2017", "password" => "pacar2017"),
        array("name" => "IDA NURCHASANAH, SE|PAGESANGAN|JAMBANGAN", "username" => "kel_pagesangan", "password_text" => "pages2017", "password" => "pages2017"),
        array("name" => "BAMBANG SOEPRIJATMODJO, SH|PAKAL|PAKAL", "username" => "kel_pakal", "password_text" => "pakal2017", "password" => "pakal2017"),
        array("name" => "NOVI TRI HARTATININSIH, S.STP|PAKIS|SAWAHAN", "username" => "kel_pakis", "password_text" => "pakis2017", "password" => "pakis2017"),
        array("name" => "INDAH PUSPARINI, SH|PANJANG JIWO|TENGGILIS MEJOYO", "username" => "kel_panjangjiwo", "password_text" => "panja2017", "password" => "panja2017"),
        array("name" => "HAJAR SULISTYONO, S.Sos,M.Si|PRADAH KALIKENDAL|DUKUH PAKIS", "username" => "kel_pradahkalikendal", "password_text" => "password2022", "password" => "password2022"),
        array("name" => "TOMY ANDRIANTO, ST|PEGIRIAN|SEMAMPIR", "username" => "kel_pegirian", "password_text" => "Pegir_2022", "password" => "Pegir_2022"),
        array("name" => "SKUNDARIO KRISTIANINDRAPUTRA, S.T.|PENELEH|GENTENG", "username" => "kel_peneleh", "password_text" => "penel2017", "password" => "penel2017"),
        array("name" => "ERDIAN SYAHRIR, SE, MM|PENJARINGANSARI|RUNGKUT", "username" => "kel_penjaringansari", "password_text" => "penja2017", "password" => "penja2017"),
        array("name" => "SAEFUDDIN ZUHRI, S.Kep.Ns, M.Kes|PERAK BARAT|KREMBANGAN", "username" => "kel_perakbarat", "password_text" => "perak2017", "password" => "perak2017"),
        array("name" => "YAYUK SRI WAHYUNI SE|TANJUNG PERAK|PABEAN CANTIAN", "username" => "kel_tanjungperak", "password_text" => "perak2017", "password" => "perak2017"),
        array("name" => "ANTONO LEGOWO, S.T.P. |PETEMON|SAWAHAN", "username" => "kel_petemon", "password_text" => "petem2017", "password" => "petem2017"),
        array("name" => "LAILATUS SAADAH L., SH|PLOSO|TAMBAKSARI", "username" => "kel_ploso", "password_text" => "ploso2017", "password" => "ploso2017"),
        array("name" => "Dra. SUWARTI|PUCANG SEWU|GUBENG", "username" => "kel_pucangsewu", "password_text" => "pucan2017", "password" => "pucan2017"),
        array("name" => "KARTIKA PRABANINGRUM S.Ak., M.A.P|KERTAJAYA|GUBENG", "username" => "kel_kertajaya", "password_text" => "pucangadi_116", "password" => "pucangadi_116"),
        array("name" => "GIN GIN GINANJAR, SP|PUTAT GEDE|SUKOMANUNGGAL", "username" => "kel_putatgede", "password_text" => "putat2017", "password" => "putat2017"),
        array("name" => "BRYAN IBNU MASKUWAIH, S.STP|PUTAT JAYA|SAWAHAN", "username" => "kel_putatjaya", "password_text" => "putat2017", "password" => "putat2017"),
        array("name" => "DODY SAMSUDDIN, SH|RUNGKUT MENANGGAL|GUNUNG ANYAR", "username" => "kel_rungkutmenanggal", "password_text" => "qwerty", "password" => "qwerty"),
        array("name" => "SAMSUL ARIFIN, SH, MM|RANGKAH|TAMBAKSARI", "username" => "kel_rangkah", "password_text" => "rangk2017", "password" => "rangk2017"),
        array("name" => "ITAQWATI OETAMI, SE, MM|ROMOKALISARI|BENOWO", "username" => "kel_romokalisari", "password_text" => "romok2017", "password" => "romok2017"),
        array("name" => "NURNANING KUSUMA FITRI, SE|RUNGKUT KIDUL|RUNGKUT", "username" => "kel_rungkutkidul", "password_text" => "rungk2017", "password" => "rungk2017"),
        array("name" => "ROSALIA RETNO BINTARTI, S.Psi|RUNGKUT TENGAH|GUNUNG ANYAR", "username" => "kel_rungkuttengah", "password_text" => "rungk2017", "password" => "rungk2017"),
        array("name" => "IWAN AKHMADI, SE|SAMBIKEREP|SAMBIKEREP", "username" => "kel_sambikerep", "password_text" => "sambikerep121", "password" => "sambikerep121"),
        array("name" => "MOESTOFA, ST|SAWAHAN|SAWAHAN", "username" => "kel_sawahan", "password_text" => "sawah2017", "password" => "sawah2017"),
        array("name" => "RIZKA FADILLAH, ST|SAWUNGGALING|WONOKROMO", "username" => "kel_sawunggaling", "password_text" => "sawun2017", "password" => "sawun2017"),
        array("name" => "Ir. OKTO NARWANTO MM|SEMEMI|BENOWO", "username" => "kel_sememi", "password_text" => "sememi2017", "password" => "sememi2017"),
        array("name" => "KENNY PIETER TUPAMAHU, S.STP, MM|SEMOLOWARU|SUKOLILO", "username" => "kel_semolowaru", "password_text" => "semol2017", "password" => "semol2017"),
        array("name" => "EKA PUJI ASTUTIE, S.Sos|SIDODADI|SIMOKERTO", "username" => "kel_sidodadi", "password_text" => "sidod2021", "password" => "sidod2021"),
        array("name" => "LPMK JAGIR|JAGIR|WONOKROMO", "username" => "lpmk_jagir", "password_text" => "sidomukti731731", "password" => "sidomukti731731"),
        array("name" => "Drs. ROEM HARTONO|SIDOTOPO WETAN|KENJERAN", "username" => "kel_sidotopowetan", "password_text" => "sidot2021", "password" => "sidot2021"),
        array("name" => "JUNAIDI ABDILLAH, S.T.|SIMOKERTO|SIMOKERTO", "username" => "kel_simokerto", "password_text" => "simok2017", "password" => "simok2017"),
        array("name" => "SATRIYO SOESANTO, ST|SIMOLAWANG|SIMOKERTO", "username" => "kel_simolawang", "password_text" => "simol2017", "password" => "simol2017"),
        array("name" => "IWAN RATMONO, SE|SIMOMULYO|SUKOMANUNGGAL", "username" => "kel_simomulyo", "password_text" => "simom2017", "password" => "simom2017"),
        array("name" => "MUKTAR H MUHAMMAD SH|SIMOMULYO BARU|SUKOMANUNGGAL", "username" => "kel_simomulyobaru", "password_text" => "simom2019", "password" => "simom2019"),
        array("name" => "KAIRUL BUDIARTO, SH|SIWALANKERTO|WONOCOLO", "username" => "kel_siwalankerto", "password_text" => "siwal2017", "password" => "siwal2017"),
        array("name" => "NOVAN NUGROHO, SST, MT|SONOKWIJENAN|SUKOMANUNGGAL", "username" => "kel_sonokwijenan", "password_text" => "sonok2017", "password" => "sonok2017"),
        array("name" => "YAYUK HERWATI, S,Sos|SUKOMANUNGGAL|SUKOMANUNGGAL", "username" => "kel_sukomanunggal", "password_text" => "sukom2017", "password" => "sukom2017"),
        array("name" => " ROIS YUNIANTO, S.Sos., M.Si|SUMBER REJO|PAKAL", "username" => "kel_sumberrejo", "password_text" => "sumbe2017", "password" => "sumbe2017"),
        array("name" => "ELVANDA DANU HERGAISWARA, S.T.|SUMURWELUT|LAKARSANTRI", "username" => "kel_sumurwelut", "password_text" => "sumur2017", "password" => "sumur2017"),
        array("name" => "HANDAYANI, S.Sos,MM|ALUN-ALUN CONTONG|BUBUTAN", "username" => "kel_alonaloncontong", "password_text" => "Surabaya1945", "password" => "Surabaya1945"),
        array("name" => "MOERITA, SH|MEDOKAN SEMAMPIR|SUKOLILO", "username" => "kel_medokansemampir", "password_text" => "Suraiya99", "password" => "Suraiya99"),
        array("name" => "CITY MANGEZONG NEGERI PERTIWI S.H.|TAMBAK SARIOSO|ASEM ROWO", "username" => "kel_tambaksarioso", "password_text" => "tamba2017", "password" => "tamba2017"),
        array("name" => "DEDY PURWITO, S.T.|TAMBAK OSO WILANGUN|BENOWO", "username" => "kel_tambakosowilangun", "password_text" => "tamba2017", "password" => "tamba2017"),
        array("name" => "AWANG WIRAWAN, S.T.|TAMBAKREJO|SIMOKERTO", "username" => "kel_tambakrejo", "password_text" => "tamba2017", "password" => "tamba2017"),
        array("name" => "MATILLA, Skep, Ns, M.H|TAMBAK WEDI|KENJERAN", "username" => "kel_tambakwedi", "password_text" => "tamba2017", "password" => "tamba2017"),
        array("name" => "AMDANY PRAPTAMA YANTONY, S.STP|TAMBAKSARI|TAMBAKSARI", "username" => "kel_tambaksari", "password_text" => "tambaksari35", "password" => "tambaksari35"),
        array("name" => "ANGGORO HIMAWAN, ST, M.T|TANAH KALI KEDINDING|KENJERAN", "username" => "kel_tanahkalikedinding", "password_text" => "tanah2017", "password" => "tanah2017"),
        array("name" => "UMMI KALSUM, SH|TANDES|TANDES", "username" => "kel_tandes", "password_text" => "tande2017", "password" => "tande2017"),
        array("name" => "MOHAMAD FERYADIWINARSO, S.T.|TANJUNGSARI|SUKOMANUNGGAL", "username" => "kel_tanjungsari", "password_text" => "tanju2017", "password" => "tanju2017"),
        array("name" => "KIKI AYU PRAMESTI, S.KM,M.Kes|TEGALSARI|TEGALSARI", "username" => "kel_tegalsari", "password_text" => "tegal2017", "password" => "tegal2017"),
        array("name" => "AGUSTINUS HERU PRASETIYO, S.T.|TEMBOK DUKUH|BUBUTAN", "username" => "kel_tembokdukuh", "password_text" => "tembo2017", "password" => "tembo2017"),
        array("name" => "TRI KARTIKA SARI, S.KM|TENGGILIS MEJOYO|TENGGILIS MEJOYO", "username" => "kel_tenggilismejoyo", "password_text" => "tenggilis1", "password" => "tenggilis1"),
        array("name" => "PRAMUDITA YUSTIANI, S.T.|GAYUNGAN|GAYUNGAN", "username" => "kel_gayungan", "password_text" => "thegayung2022", "password" => "thegayung2022"),
        array("name" => "LPMK TAMBAKREJO|TAMBAKREJO|SIMOKERTO", "username" => "lpmk_tambakrejo", "password_text" => "tsiraya_03", "password" => "tsiraya_03"),
        array("name" => "M. NURUL HUDA, S.T.|MADE|SAMBIKEREP", "username" => "kel_made", "password_text" => "u8au92", "password" => "u8au92"),
        array("name" => "Dra. SRI BAHARIA|WARU GUNUNG|KARANG PILANG", "username" => "kel_warugunung", "password_text" => "warug2017", "password" => "warug2017"),
        array("name" => "Drs. GATOT SUBROTO, MM|WIYUNG|WIYUNG", "username" => "kel_wiyung", "password_text" => "wiyun2017", "password" => "wiyun2017"),
        array("name" => "PRIMA SRI POERWIENDARI SE|WONOKROMO|WONOKROMO", "username" => "kel_wonokromo", "password_text" => "wonok2017", "password" => "wonok2017"),
        array("name" => "ARI HARDINI ST, M.M|WONOREJO|RUNGKUT", "username" => "kel_wonorejorungkut", "password_text" => "wonor2017", "password" => "wonor2017"),
        array("name" => "NOERCHOLIS YASIN SUTRISNO, S.E.|WONOREJO|TEGALSARI", "username" => "kel_wonorejotegalsari", "password_text" => "wonor2017", "password" => "wonor2017"),
        array("name" => "LPMK GUBENG|GUBENG|GUBENG", "username" => "lpmk_gubeng", "password_text" => "yadi1968", "password" => "yadi1968"),
        array("name" => "LPMK BERINGIN|BERINGIN|SAMBIKEREP", "username" => "lpmk_beringin", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023"),
        array("name" => "LPMK ALUN-ALUN CONTONG|ALUN-ALUN CONTONG|BUBUTAN", "username" => "lpmk_alun-aluncontong", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023"),
        array("name" => "LPMK DR. SOETOMO|DR. SOETOMO|TEGALSARI", "username" => "lpmk_dr.soetomo", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023"),
        array("name" => "LPMK KEJAWAAN PUTIH TAMBAK|KEJAWAAN PUTIH TAMBAK|MULYOREJO", "username" => "lpmk_kejawaanputihtambak", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023"),
        array("name" => "LPMK TEGALSARI WONOREJO|WONOREJO|TEGALSARI", "username" => "lpmk_tegalsariwonorejo", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023"),
        array("name" => "LPMK RUNGKUT WONOREJO|WONOREJO|RUNGKUT", "username" => "lpmk_rungkutwonorejo", "password_text" => "aizakmi_2023", "password" => "aizakmi_2023")
    );
    public $permissions = [
        ['name' => 'create-usulan-banmod'],
        ['name' => 'read-usulan-banmod'],
        ['name' => 'delete-usulan-banmod'],
        ['name' => 'update-usulan-banmod'],
    ];

    public $role = [
        'name' => 'Kelurahan'
    ];

    public function run()
    {
        $role = Role::create($this->role);
        foreach ($this->permissions as $permission) {
            $permite = Permission::create($permission);
            $role->givePermissionTo($permission);
        }

        foreach ($this->users as $user) {
            $userx=User::create([
                'name'=>$user['name'],
                'password'=>Hash::make($user['password']),
                'username'=>$user['username'],
                'password_text'=>$user['password'],
            ]);
            $userx->assignRole($role);
        }
    }
}
